### ISSUE TITLE
Date on latest article is wrong

### ISSUE THREAD

**Issue by g00glen00b** [LunarWatcher/lunarwatcher.github.io#19]
It appears that if you use two digit years, the interpreter thinks the date is provided as `YY.MM.DD` in stead of `DD.MM.YY`. Due to that, your latest post appears to be released on 19 february 2020 in stead of 20 february 2019.

<img width="1055" alt="screenshot 2019-03-05 14 29 09" src="https://user-images.githubusercontent.com/4865705/53808642-147bbd80-3f53-11e9-8ff7-7709947f9fc3.png">

**Comment by LunarWatcher** [comment]
Thanks for the heads-up - I'm not used to the date format ^^" I got the file format right at least, but I have no clue what I was thinking ^^"
