### ISSUE TITLE
Grammatical error in Why I'm leaving Stack Exchange

### ISSUE THREAD

**Issue by JL2210** [LunarWatcher/lunarwatcher.github.io#24]
Under *Old background*, this sentence is present:

*Unfortunately, SO being considered elitist and toxic results in some users (not always new) going on a rant about how toxic SO in, ironically, a toxic way.*

There should be an *is* here:

*about how toxic SO **is** in, ironically, a toxic way*

**Comment by LunarWatcher** [comment]
Thanks. Some of these typos slip through some times. They'er hard to catch ^^"
